wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    framework: ignite
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.12
    start_time: 1656400670
    t:
      1:
      - 1
      - 5
      - 10
      - 41
      - 48
      - 53
      - 55
      2:
      - 1
      - 5
      - 10
      - 41
      - 48
      - 53
      - 55
      4: 3.8.12
      5: 0.12.19
      8:
      - 2
      - 5
amp:
  desc: null
  value: false
batch_size:
  desc: null
  value: 1
epochs:
  desc: null
  value: 1
img_scale:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 1.0e-05
test_num:
  desc: null
  value: 73
